# Generated by Django 3.1.4 on 2020-12-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='example',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
